# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-12'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.15.1'
  displayName: 'Install Node'

- script: npm install
  displayName: 'npm install'

- script: npm i -g expo-cli
  displayName: 'install expo'
  
- script: expo start --web
  displayName: 'start'